### ISSUE TITLE
No such file or directory: 'data/DeepBD/features'

### ISSUE THREAD

**Issue by ai-sta-website** [deepbindiff/DeepBinDiff#5]
Hello there,

Thanks a lot for providing such a nice tool to use. I am writing to inquire an error encountered when running this tool. Here is the error message I received:

```
 python3 src/deepbindiff.py --input1 experiment_data/coreutils/binaries/coreutils-7.6-O0/ls --input2 experiment_data/coreutils/binaries/coreutils-7.6-O3/ls --outputDir output/
....
....
Initialized
Average loss at step  0 :  134.17404174804688
Average loss at step  2000 :  5.122461198568344
Average loss at step  4000 :  3.3189247410297393
Average loss at step  6000 :  3.2604737248420714
Traceback (most recent call last):
  File "src/deepbindiff.py", line 230, in <module>
    main()
  File "src/deepbindiff.py", line 223, in main
    copyEverythingOver(outputDir, 'data/DeepBD/')
  File "src/deepbindiff.py", line 172, in copyEverythingOver
    copyfile(src_dir + node_features, dst_dir + node_features)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'data/DeepBD/features'
```

Can anyone shed some lights on this? Thank you very much!

**Comment by yueduan** [comment]
Hi, I believe this is due to the hard-code path 'data/DeepBD/' missing. Had to admit my code is a bit messy. Could you please create the directory 'data/DeepDB' and try again?

**Comment by ai-sta-website** [comment]
@yueduan thank you for your prompt reply. I make the directory `data/DeepDB` but still, the same error occurs:

```
Average loss at step  6000 :  3.260503334522247
Traceback (most recent call last):
  File "src/deepbindiff.py", line 230, in <module>
    main()
  File "src/deepbindiff.py", line 223, in main
    copyEverythingOver(outputDir, 'data/DeepBD/')
  File "src/deepbindiff.py", line 172, in copyEverythingOver
    copyfile(src_dir + node_features, dst_dir + node_features)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'data/DeepBD/features'
```

**Comment by yueduan** [comment]
Hi, Could you please make sure there exists a file 'features' in your --outputDir? Ln.221 in deepbindiff.py is supposed to generate 'features' file. And then the 'copyEverythingOver' function can copy it into another 'data/DeepBD' directory.

**Comment by random-friendly-dude** [comment]
Hello,

Indeed, I do find a `features` in the output dir:

```
➜  DeepBinDiff git:(master) ✗ python3 src/deepbindiff.py --input1 experiment_data/coreutils/binaries/coreutils-7.6-O0/ls --input2 experiment_data/coreutils/binaries/coreutils-7.6-O3/ls --outputDir output/
➜  DeepBinDiff git:(master) ✗ ls output
data  edgelist  edgelist_merged_tadw  features  nodeIndexToCode
```

**Comment by random-friendly-dude** [comment]
And I have also created an empty `features` as the output:

```
➜  DeepBinDiff git:(master) ✗ touch data/DeepDB/features
➜  DeepBinDiff git:(master) ✗
```

**Comment by jecompton** [comment]
The harcoded paths haven't been fixed, so it still fails. I don't think this issue should be closed.

Also, to the dxyslecis out there, it is DeepBD. 'BD'. 'BD'! Not DB.
