### ISSUE TITLE
code KeyError

### ISSUE THREAD

**Issue by 0xling** [deepbindiff/DeepBinDiff#9]
I run this command
```
python3 src/deepbindiff.py --input1 ./experiment_data/findutils/binaries/findutils-4.41-O2/find --input2 ./experiment_data/findutils/binaries/findutils-4.6-O2/find --outputDir ./result
```

It has a KeyError
```
Traceback (most recent call last):
  File "src/deepbindiff.py", line 243, in <module>
    main()
  File "src/deepbindiff.py", line 224, in main
    block_embeddings = cal_block_embeddings(blockIdxToTokens, blockIdxToOpcodeNum, blockIdxToOpcodeCounts, insToBlockCounts, tokenEmbeddings, reversed_dictionary)
  File "src/deepbindiff.py", line 118, in cal_block_embeddings
    tf_weight = opcodeCounts[token] / opcodeNum
KeyError: 'and'
```

**Comment by yueduan** [comment]
fixed
